storagenode/hashstore: make ConfigTest os agnostic
As Egon reported, the test is failing on Windows due to different separator:

https://review.dev.storj.tools/c/storj/storj/+/16334?tab=comments

> This test is failing on windows with:

```

Change-Id: Iaa84207c2d95f024a9ecb34432439d9f45d1a590
--- FAIL: TestConfig (0.00s)
    config_test.go:18:
                Error Trace:    s:/core/storj/storagenode/hashstore/config_test.go:18
                Error:          Not equal:
                                expected: "/path/to/storage/logs"
                                actual  : "\\path\\to\\storage\\logs"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -/path/to/storage/logs
                                +\path\to\storage\logs
                Test:           TestConfig
FAIL
exit status 1
FAIL    storj.io/storj/storagenode/hashstore    1.160s
```

Change-Id: I0495cd27c0d6c5479a70a309b37d1edc5bcb9ade