satellite/payments: TestTransactionsDBList not ready for Spanner
This has been causing many failures on main with errors like:

    --- FAIL: TestTransactionsDBList (7.16s)
    --- FAIL: TestTransactionsDBList/insert_and_list_transactions (0.00s)
    --- FAIL: TestTransactionsDBList/insert_and_list_transactions/Spanner (7.16s)

        logger.go:146: 2024-08-08T16:22:50.660Z	DEBUG	creating	{"suffix": "20e005bcfb52"}
        logger.go:146: 2024-08-08T16:22:50.834Z	DEBUG	db	Connected to:	{"db source": "projects/storj-build/instances/test-instance/databases/testtrans_20e005bcfb52_t0_c9a4"}
        transactions_test.go:76:
        	    Error Trace:	/tmp/workspace/storj-gerrit-verify/satellite/payments/billing/transactions_test.go:76
        	            				    /tmp/workspace/storj-gerrit-verify/satellite/satellitedb/satellitedbtest/run.go:278
        	    Error:      	Received unexpected error:
        	            	    satellitedb: Unable to insert new billing transaction after several retries: <nil>
        	            		    storj.io/storj/satellite/satellitedb.billingDB.Insert:90
        	            		    storj.io/storj/satellite/payments/billing_test.TestTransactionsDBList.func1.1:75
        	            		    storj.io/storj/satellite/satellitedb/satellitedbtest.Run.func1:278
        	            		    testing.tRunner:1689
        	    Test:       	TestTransactionsDBList/insert_and_list_transactions/Spanner

Upon review, it looks like the billing_transactions table relies on a
SERIAL type for its primary key. Incrementing counters are bad news on
distributed databases like Spanner, so my suspicion is that there are
cases where GET_NEXT_SEQUENCE_VALUE does not work right and produces a
conflicting value, causing the AlreadyExists error and the retry loop in
(billingDB).Insert().

The billing_transactions table should probably use a UUID primary key
instead.

Change-Id: Ibc04a41b711fe11e5575abbbbf6b1366942e6fbe